/// Flutter icons TreeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TreeIcons
///      fonts:
///       - asset: fonts/TreeIcons.ttf
///
/// 
///

// Flutter imports:
import 'package:flutter/widgets.dart';

class TreeIcons {
  TreeIcons._();

  static const _kFontFam = 'TreeIcons';
  static const String? _kFontPkg = null;

  static const IconData left_md = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_md = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_love = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_map = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lotus = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_lotus = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_earth = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulleted_list_2 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_bulleted_list_2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData so_person = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
